---
# tasks file for ufw
- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- name: ufw add ssh in rule
  ufw:
    rule: allow
    direction: in
    src: "{{ item }}"
    to_port: 22
  loop: "{{ ufw_in_ssh_ip }}"
  notify: 
    - enable ufw service
    - enable ufw

